### PR TITLE
Add Helix and Kakoune themes to README

### PR DESCRIPTION
**Pull request by Qeatrix**
Themes I wrote for Helix and Kakoune

### CODE REVIEW

**Comment by 0neGal** [comment]
I'm quite uncertain why you made a PR for a repository that hasn't had a commit in over 3 years, a repository with 0 stars and 0 people watching it (not counting you and me), and also a repository that is just a README linking to other repositories, except the links are outdated and lead to a 404 page instead.

**Comment by Qeatrix** [comment]
Because I really like whiteout, and you are the original developer of it.

**Comment by 0neGal** [comment]
Except, I really am not, I took the [Tomorrow colorscheme](https://github.com/ccharles/Tomorrow-Theme) as stated in the README, and changed the values slightly. Furthermore, the actual hex values (beyond shades of black and white) have never been fully published (from what I remember), as the actual values were always set through my own system in my dotfiles with Xresources, and now a completely new tool. That or through the GTK theme which never got published, and remains in my private dotfiles.

The only thing I ever published was a tiny `userChrome.css` theme for Firefox (a browser I have not used in years) which I can't even recall if it works by itself, a Micro theme (an editor I haven't used in years) and a Ulauncher theme (a launcher I haven't used in years)

And the Micro theme uses your terminal's colorscheme.

Point being, the few changes I made to make Whiteout have never actually been published. I could go back in my dotfiles' commit history and find the last time I was using this colorscheme if I had to, but I no longer use it. I instead have switched to a colorscheme I built myself, still private in my dotfiles. It is similar to Whiteout's pastel like colors, and is still primarily built for light mode use, but it also features a dark mode.

Ultimately my point is that, I don't see much reason to add to this repository, and the only reason it's not archived is because I've forgotten to archive it. So feel free to use the colorscheme for your own stuff :)

**Comment by Qeatrix** [comment]
Yes, I noticed that the theme for Micro uses the colors of the terminal. That's why I wrote the theme for Alacritty. I really liked this theme a lot, thanks for letting me use it however I want. In that case I apologize for the inconvenience

**Comment by 0neGal** [comment]
No need to apologize, not much of an inconvenience, I actually thought this repo was archived years ago... So you did remind me of that...

**Pull request closed without merging**
